/** Project-local pi wiring. The caller stages the copied harness before invoking this. */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";

const EXTENSIONS = ["architect-tools", "dev-tools", "model-tier", "path-gate", "web"] as const;
const ROLE_EXTENSION = /subagentOnlyExtensions: ~\/\.pi\/agent\/hosts\/pi\/extensions\/path-gate\/([\w-]+\.ts)/g;

/** A path written into the project must not depend on the installer's location. */
function localPath(from: string, to: string): string {
  const path = relative(from, to).split(sep).join("/");
  return path.startsWith(".") ? path : `./${path}`;
}

function putNew(path: string, content: string): void {
  if (existsSync(path)) throw new Error(`pi project install refused existing file: ${path}`);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

/**
 * Bind only the selected pi host to a staged project. Common copying,
 * ownership, and publication are the init core's responsibility.
 */
export function installProjectPi(target: string, harnessRoot: string): void {
  const project = resolve(target);
  const harness = resolve(harnessRoot);
  if (!harness.startsWith(`${project}${sep}`)) {
    throw new Error("pi project install requires a harness copy inside the project");
  }

  const extensionDir = join(harness, "hosts", "pi", "extensions");
  const agentDir = join(harness, "agents");
  const skillDir = join(harness, "skills");
  for (const path of [...EXTENSIONS.map((name) => join(extensionDir, `${name}.ts`)), agentDir, skillDir]) {
    if (!existsSync(path)) throw new Error(`pi project install missing copied harness resource: ${path}`);
  }

  const loader = join(project, ".pi", "extensions", "bounded", "index.ts");
  const settings = join(project, ".pi", "settings.json");
  const roles = readdirSync(agentDir).filter((name) => name.endsWith(".md")).sort();
  const destinations = [loader, settings, ...roles.map((name) => join(project, ".pi", "agents", name))];
  for (const path of destinations) {
    if (existsSync(path)) throw new Error(`pi project install refused existing file: ${path}`);
  }

  // The loader itself uses only Node builtins. A fresh clone has no local
  // node_modules yet, so static imports of the full adapter would fail before
  // its setup tool could exist. After the two pinned installs, pi.reload()
  // loads this same file again and takes the full branch.
  const imports = EXTENSIONS.map((name) =>
    `    import(${JSON.stringify(localPath(dirname(loader), join(extensionDir, `${name}.ts`)))})`,
  );
  const loaderText = [
    "// Generated by Bounded. Dependency-free bootstrap, then the full adapter.",
    'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";',
    'import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, writeFileSync } from "node:fs";',
    'import { execFile } from "node:child_process";',
    'import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";',
    'import { fileURLToPath } from "node:url";',
    'import { promisify } from "node:util";',
    "",
    'const project = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");',
    'const harness = join(project, ".bounded", "harness");',
    'const ready = () => existsSync(join(project, ".bounded", "setup-complete")) &&',
    '  existsSync(join(project, "node_modules", ".package-lock.json")) &&',
    '  existsSync(join(harness, "node_modules", ".package-lock.json"));',
    'const leadProcess = (cwd: string) => resolve(cwd) === project && process.env["PI_SUBAGENT_CHILD"] !== "1";',
    'const exec = promisify(execFile);',
    '',
    'function note(verdict: "pass" | "block", summary: string): void {',
    '  try {',
    '    const path = join(project, ".bounded", "guard-log.jsonl");',
    '    mkdirSync(dirname(path), { recursive: true });',
    '    appendFileSync(path, JSON.stringify({ ts: new Date().toISOString(), guard: "team-lead", verdict, summary }) + "\\n");',
    '  } catch { /* logging cannot weaken the gate */ }',
    '}',
    '',
    'function setupAllowed(): boolean {',
    '  // A completed install may be repaired if its dependency trees were removed.',
    '  if (existsSync(join(project, ".bounded", "setup-complete"))) return true;',
    '  if (existsSync(join(project, ".bounded", "active-ticket")) ||',
    '      existsSync(join(project, ".bounded", "contract-checksums.json"))) return false;',
    '  const tickets = join(project, ".bounded", "tickets");',
    '  if (existsSync(tickets) && readdirSync(tickets, { withFileTypes: true }).some((entry) =>',
    '    entry.isDirectory() && existsSync(join(tickets, entry.name, "contract-checksums.json")))) return false;',
    '  const log = join(project, ".bounded", "guard-log.jsonl");',
    '  if (!existsSync(log)) return true;',
    '  for (const line of readFileSync(log, "utf8").split("\\n")) {',
    '    if (!line.trim()) continue;',
    '    try { if (JSON.parse(line).guard === "run-start") return false; }',
    '    catch { return false; }',
    '  }',
    '  return true;',
    '}',
    '',
    'function projectRead(path: unknown): boolean {',
    '  if (typeof path !== "string" || !path) return false;',
    '  const target = resolve(project, path);',
    '  const rel = relative(project, target);',
    '  if (rel === ".." || rel.startsWith(".." + sep) || isAbsolute(rel)) return false;',
    '  if (rel.split(sep).includes(".git")) return false;',
    '  try {',
    '    const actual = relative(realpathSync(project), realpathSync(target));',
    '    return actual !== ".." && !actual.startsWith(".." + sep) && !isAbsolute(actual) &&',
    '      !actual.split(sep).includes(".git");',
    '  } catch { return false; }',
    '}',
    '',
    'function bootstrap(pi: ExtensionAPI): void {',
    '  pi.registerTool({',
    '    name: "lead_setup", label: "Install project dependencies",',
    '    description: "Install the project and local harness dependencies from their committed lockfiles, then activate the full Bounded guard.",',
    '    parameters: { type: "object", properties: {}, additionalProperties: false } as any,',
    '    async execute(_id, _params, signal, _onUpdate, ctx) {',
    '      if (!leadProcess(ctx.cwd) || !setupAllowed()) return { content: [{ type: "text" as const, text: "team-lead: setup is available only to the project-root lead before the first run" }], details: { ok: false } };',
    '      try {',
    '        await exec("npm", ["ci"], { cwd: project, signal, maxBuffer: 2 * 1024 * 1024 });',
    '        await exec("npm", ["ci", "--prefix", ".bounded/harness"], { cwd: project, signal, maxBuffer: 2 * 1024 * 1024 });',
    '        if (!existsSync(join(project, "node_modules", ".package-lock.json")) ||',
    '            !existsSync(join(harness, "node_modules", ".package-lock.json")))',
    '          throw new Error("npm ci returned without both dependency trees");',
    '        writeFileSync(join(project, ".bounded", "setup-complete"), "complete\\n");',
    '        note("pass", "team-lead: project and local harness dependencies installed from lockfiles");',
    '        await ctx.reload();',
    '        return { content: [{ type: "text" as const, text: "Dependencies installed; full Bounded guard is active." }], details: { ok: true } };',
    '      } catch (error) {',
    '        const reason = `team-lead: dependency setup failed: ${error instanceof Error ? error.message : String(error)}`;',
    '        note("block", reason.slice(-1200));',
    '        return { content: [{ type: "text" as const, text: reason.slice(-1200) }], details: { ok: false } };',
    '      }',
    '    },',
    '  });',
    '  pi.on("session_start", (_event, ctx) => {',
    '    const kept = pi.getActiveTools().filter((name) => name === "read" || name === "ls" ||',
    '      (name === "lead_setup" && leadProcess(ctx.cwd)));',
    '    pi.setActiveTools(kept);',
    '  });',
    '  pi.on("tool_call", (event, ctx) => {',
    '    if (event.toolName === "lead_setup" && leadProcess(ctx.cwd) && setupAllowed()) return undefined;',
    '    if ((event.toolName === "read" || event.toolName === "ls") &&',
    '        projectRead((event.input as Record<string, unknown>)["path"])) return undefined;',
    '    const reason = `team-lead: ${event.toolName} is unavailable until pinned dependencies are installed`;',
    '    note("block", reason);',
    '    return { block: true, reason };',
    '  });',
    '}',
    '',
    'export default async function (pi: ExtensionAPI): Promise<void> {',
    '  if (!ready()) { bootstrap(pi); return; }',
    '  try {',
    '    const loaded = await Promise.all([',
    ...imports.map((line) => `${line},`),
    '    ]);',
    '    for (const extension of loaded) await extension.default(pi);',
    '    // pi-subagents defaults to user-level roles; this project owns its roles.',
    '    pi.on("tool_call", (event) => {',
    '      if (event.toolName !== "subagent") return undefined;',
    '      const input = event.input as Record<string, unknown>;',
    '      if (input.agentScope === undefined) input.agentScope = "project";',
    '      return undefined;',
    '    });',
    '  } catch (error) {',
    '    const reason = `team-lead: full adapter load failed: ${error instanceof Error ? error.message : String(error)}`;',
    '    note("block", reason.slice(-1200));',
    '    bootstrap(pi);',
    '  }',
    "}",
    "",
  ].join("\n");

  const settingsText = JSON.stringify({
    packages: ["npm:pi-subagents@0.52.1"],
    skills: [localPath(dirname(settings), skillDir), localPath(dirname(settings), join(harness, "packs"))],
    subagents: { disableBuiltins: true },
  }, null, 2) + "\n";

  const renderedRoles = roles.map((name) => {
    const source = readFileSync(join(agentDir, name), "utf8");
    const content = source.replace(ROLE_EXTENSION, (_match, roleFile: string) => {
      const roleExtension = join(extensionDir, "path-gate", roleFile);
      if (!existsSync(roleExtension)) throw new Error(`pi project install missing role extension: ${roleExtension}`);
      return `subagentOnlyExtensions: ${localPath(project, roleExtension)}`;
    });
    if (content.includes("~/.pi/agent/")) {
      throw new Error(`pi project install cannot render global path in ${name}`);
    }
    return { path: join(project, ".pi", "agents", name), content };
  });

  putNew(loader, loaderText);
  putNew(settings, settingsText);
  for (const role of renderedRoles) putNew(role.path, role.content);
}
